name: Preview Release

on:
  push:
    branches:
      - develop

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  pre-release:
    name: Pre-Release
    runs-on: ubuntu-latest
    permissions:
      actions: write
      pull-requests: write
      statuses: write
      contents: write
      issues: write
      security-events: write
      pages: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Create PreRelease Pull Request
        uses: changesets/action@v1
        id: changesets
        with:
          title: "chore(pre-release): bump version"
          commit: "chore(pre-release): bump version"
          version: "pnpm changeset version"
          publish: "echo \"Deploy to preview environment\""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test Debug
        if: steps.changesets.outputs.published == 'true'
        run: echo "Launch CircleCI deploy pipeline"
