# Testing purpose: trigger pipeline on each merge on main
on:
  push:
    branches:
      - main

jobs:
  trigger-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.1.0
        with:
          GHA_Meta: "[{\"name\":\"@sp/card-app\",\"version\":\"0.2.1\"},{\"name\":\"@sp/card-shell\",\"version\":\"0.0.8\"}]"
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
